config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :necos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/neco.rb
class Neco < ApplicationRecord
  belongs_to :user
  attachment :image
  
  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :necos, dependent: :destroy
  
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/necos_controller.rb
class NecosController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @necos = Neco.all
  end

  def show
    @neco = Neco.find(params[:id])
  end

  def new
    @neco = Neco.new
  end
  
  def create
    @neco = Neco.new(neco_params)
    @neco.user_id = current_user.id
    if @neco.save
      redirect_to neco_path(@neco), notice: '投稿に成功しました。'
    else
      render :new
    end
  end
  
  def edit
    @neco = Neco.find(params[:id])
    if @neco.user != current_user
      redirect_to necos_path, alert: '不正なアクセスです。'
    end
  end
  
  def update
    @neco = Neco.find(params[:id])
    if @neco.update(neco_params)
      redirect_to neco_path(@neco), notice: '更新に成功しました。'
    else
      render :edit
    end
  end
  
 def destroy
   neco = Neco.find(params[:id])
   neco.destroy
   redirect_to necos_path
 end
  
  private
  def neco_params
    params.require(:neco).permit(:title, :body, :image)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: '不正なアクセスです。'
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: '更新に成功しました。'
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/necos_helper.rb
module NecosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1">NECOJIMAN</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column">
          <figure>
            <div class="main-image"></div>
          </figure>
        </div>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>necojiman</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4">NECOJIMAN</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "ネコ一覧", necos_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "ネコ投稿", new_neco_path, class: "navbar-item button is-warning is-light" %>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ネコ好き一覧", users_path, class: " button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "ネコ一覧", necos_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "ネコグラマー一覧", users_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/necos/edit.html.erb
   
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
       ネコ編集
      </h1>
    </div>
  </div>
</section>

<% if @neco.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@neco.errors.count, "error") %>未入力の項目があります。</h2>
    <ul>
      <% @neco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @neco do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/necos/index.html.erb
   
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ネコ一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @necos.each do |neco| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to neco_path(neco) do %>
                  <%= attachment_image_tag neco, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= link_to user_path(neco.user.id) do %>
                      <%= attachment_image_tag neco.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                    <% end %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%= link_to neco.user.username, user_path(neco.user.id) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= neco.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/necos/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規ネコ作成
      </h1>
    </div>
  </div>
</section>

<% if @neco.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@neco.errors.count, "error") %>未入力の項目があります。</h2>
    <ul>
      <% @neco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @neco do |f| %>
          <div class="field">
            <%= f.label :title, "タイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "撮影日記", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/necos/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ネコ詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @neco, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @neco.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>撮影日記</th>
                </tr>
                <tr>
                  <td><%= simple_format @neco.body %></td>
                </tr>
              </table>
              <% if @neco.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_neco_path(@neco), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @neco.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @neco.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@neco.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @neco.user.username %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>

<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %>未入力の項目があります。</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ネコ好き一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.necos.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                  <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.necos.each do |neco| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to neco_path(neco) do %>
                  <%= attachment_image_tag neco, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to neco_path(neco), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このネコを見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_neco_path(neco), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このネコを編集する
                    <% end %>
                    <%= link_to neco_path(neco), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このネコを削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= neco.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>